{% set version = "5.3.0" %}

package:
  name: singlejar
  version: {{ version }}

source:
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: ee801491ff0ec3a562422322a033c9afe8809b64199e4a94c7433d4e14e6b921
    patches:
      # Keep these patches in sync with the ones from bazel-feedstock.
      - 0001-allow-args-to-be-passed-to-bazel_build.patch
      - 0002-Build-with-native-dependencies.patch
      - 0003-Parametrize-LIBPROTOBUF_VERSION.patch
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-darwin-x86_64  # [build_platform == "osx-64"]
    sha256: 5bc66d82dccd251198b1dd87c329343a1c26809b24248d189e612a920eff9c1d  # [build_platform == "osx-64"]
    fn: bazel  # [build_platform == "osx-64"]
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64  # [build_platform == "osx-arm64"]
    sha256: 9def16fa1d4652de8329dd3d0e26d4d6a8479ca472a470ac846d83f475a284fb  # [build_platform == "osx-arm64"]
    fn: bazel  # [build_platform == "osx-arm64"]
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64  # [build_platform == "linux-64"]
    sha256: d64f1f0bd6a80f5b7282fd5fc84a1fd37ae9feea2a95e06d8c261123c2f80a78  # [build_platform == "linux-64"]
    fn: bazel  # [build_platform == "linux-64"]

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain
    - openjdk
    - libprotobuf
  host:
    - libprotobuf

test:
  commands:
    - test -f $PREFIX/bin/singlejar
    - test -f $PREFIX/bin/singlejar_local

about:
  home: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: A tool for generating singleton jars

extra:
  recipe-maintainers:
    - xhochy
    - h-vetinari
    - conda-forge/bazel
