{% set version = "5.3.2" %}

package:
  name: singlejar
  version: {{ version }}

source:
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: 3880ad919592d1e3e40c506f13b32cd0a2e26f129d87cb6ba170f1801d7d7b82
    patches:
      # Keep these patches in sync with the ones from bazel-feedstock.
      - 0001-allow-args-to-be-passed-to-bazel_build.patch
      - 0002-Build-with-native-dependencies.patch
      - 0003-Parametrize-LIBPROTOBUF_VERSION.patch
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-darwin-x86_64  # [build_platform == "osx-64"]
    sha256: c8cebf3604c18cc2c299f72635d47ebdc798c8e59f3210c71f05485abc8ddf69  # [build_platform == "osx-64"]
    fn: bazel  # [build_platform == "osx-64"]
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64  # [build_platform == "osx-arm64"]
    sha256: 1bdfe8333f3d2f62405282b09defe7734f928ef6d9598844147249ee754d3d5b  # [build_platform == "osx-arm64"]
    fn: bazel  # [build_platform == "osx-arm64"]
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64  # [build_platform == "linux-64"]
    sha256: 674c34f7681f132153bc603bd5bb2c54a1aea64349a304e1326e54cfd0366131  # [build_platform == "linux-64"]
    fn: bazel  # [build_platform == "linux-64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain
    - openjdk
    - libprotobuf
  host:
    - libprotobuf

test:
  commands:
    - test -f $PREFIX/bin/singlejar
    - test -f $PREFIX/bin/singlejar_local

about:
  home: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: A tool for generating singleton jars

extra:
  recipe-maintainers:
    - xhochy
    - h-vetinari
    - conda-forge/bazel
