{% set version = "8.7.0" %}

{% set base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: singlejar
  version: {{ version }}

source:
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: 75ed5aa189fd687e6e7c289ad86a3851844965a6c1479b7a5ce9b846a6e461bc
    patches:
      # Keep these patches in sync with the relevant ones from bazel-feedstock.
      - patches/0001-allow-args-to-be-passed-to-bazel_build.patch
      - patches/0002-Build-with-native-dependencies.patch
      - patches/0003-use-C-17.patch

  - fn: bazel-{{ version }}
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64   # [build_platform == "linux-64"]
    sha256: 83a0ec39f7ef3938b651c82d77ababfe96a9e4b9b566d7633f1c5f2ee9d2c8ed   # [build_platform == "linux-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-x86_64  # [build_platform == "osx-64"]
    sha256: ac6175783fc463cc8f764353a52d4136550834d8855808086e7e21514f3c6ccd   # [build_platform == "osx-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64   # [build_platform == "osx-arm64"]
    sha256: fb49e0b21742c29ae1b413396af49d5a9cc1d0d7b6b958df4335225ad5f8d4ad   # [build_platform == "osx-arm64"]

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain >=0.2.0,<0.5.9
    - openjdk
    - libprotobuf
    - sed
  host:
    - libabseil
    - libprotobuf
    - protobuf-bazel-rules

test:
  commands:
    - test -f $PREFIX/bin/singlejar
    - test -f $PREFIX/bin/singlejar_local

about:
  home: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: A tool for generating singleton jars

extra:
  recipe-maintainers:
    - xhochy
    - h-vetinari
    - conda-forge/bazel
