{% set name = "singlejar" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: 820a94dbb14071ed6d8c266cf0c080ecb265a5eea65307579489c4662c2d582a
    patches:
      # Keep these patches in sync with the ones from bazel-feedstock.
      - 0001-allow-args-to-be-passed-to-bazel_build.patch
      - 0002-Build-with-native-dependencies.patch
      - 0003-Parametrize-LIBPROTOBUF_VERSION.patch
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-darwin-x86_64  # [build_platform == "osx-64"]
    sha256: dbf2f955fe5ebe79aded90a0b400a71853feaf0772fb2fc95f5c5f2ba6804b98  # [build_platform == "osx-64"]
    fn: bazel  # [build_platform == "osx-64"]
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64  # [build_platform == "osx-arm64"]
    sha256: 8ab6cf61e8fa5c8dadb3873315c2865ce5e2b5bcf6a165dc7368554dbaf0a520  # [build_platform == "osx-arm64"]
    fn: bazel  # [build_platform == "osx-arm64"]
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64  # [build_platform == "linux-64"]
    sha256: 8726379b76dc69bb652f0dea8658f2e0304a98dbbaf8a773c6726a3052ef80d5  # [build_platform == "linux-64"]
    fn: bazel  # [build_platform == "linux-64"]

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain
    - openjdk
    - libprotobuf
  host:
    - libprotobuf

test:
  commands:
    - test -f $PREFIX/bin/singlejar
    - test -f $PREFIX/bin/singlejar_local

about:
  home: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: A tool for generating singleton jars

extra:
  recipe-maintainers:
    - xhochy
