{% set version = "6.0.0" %}

package:
  name: singlejar
  version: {{ version }}

source:
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: 7bc0c5145c19a56d82a08fce6908c5e1a0e75e4fbfb3b6f12b4deae7f4b38cbc
    patches:
      # Keep these patches in sync with the ones from bazel-feedstock.
      - 0001-allow-args-to-be-passed-to-bazel_build.patch
      - 0002-Build-with-native-dependencies.patch
      - 0003-Parametrize-LIBPROTOBUF_VERSION.patch
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-darwin-x86_64  # [build_platform == "osx-64"]
    sha256: 43be52ddf23cb58a45f0c0e5586e2d04a58e6662d5413062f333848296ebcbd7  # [build_platform == "osx-64"]
    fn: bazel  # [build_platform == "osx-64"]
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64  # [build_platform == "osx-arm64"]
    sha256: 2336caab0cce8b2b4f4e802d566950f1c8da9248b463bd310995076f02d66727  # [build_platform == "osx-arm64"]
    fn: bazel  # [build_platform == "osx-arm64"]
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64  # [build_platform == "linux-64"]
    sha256: 17e2a2347b462f446803931e94fdc51630176fbbcecc08c9db293b9fb46d58b0  # [build_platform == "linux-64"]
    fn: bazel  # [build_platform == "linux-64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain
    - openjdk
    - libprotobuf
  host:
    - libprotobuf

test:
  commands:
    - test -f $PREFIX/bin/singlejar
    - test -f $PREFIX/bin/singlejar_local

about:
  home: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: A tool for generating singleton jars

extra:
  recipe-maintainers:
    - xhochy
    - h-vetinari
    - conda-forge/bazel
