{% set version = "8.6.0" %}

{% set base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: singlejar
  version: {{ version }}

source:
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: 13a84586429b6084b13bd5040d78deda58d523012151e71e7d4be0c63dd831f9
    patches:
      # Keep these patches in sync with the relevant ones from bazel-feedstock.
      - patches/0001-allow-args-to-be-passed-to-bazel_build.patch
      - patches/0002-Build-with-native-dependencies.patch
      - patches/0003-use-C-17.patch

  - fn: bazel-{{ version }}
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64   # [build_platform == "linux-64"]
    sha256: 02c355741012603b703e2a8d07ded1212f92ec6eacdabdd552695f8083e7a594   # [build_platform == "linux-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-x86_64  # [build_platform == "osx-64"]
    sha256: 6a6d0a42d62fc3a4a391d0b9976f750191ccb9afa7b084e78d0daa0422b202d0   # [build_platform == "osx-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64   # [build_platform == "osx-arm64"]
    sha256: 61776a387f2ea2a515eb92bc1c520b6af6451148216244058f6ee2b4c012cd89   # [build_platform == "osx-arm64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain >=0.2.0
    - openjdk
    - libprotobuf
    - sed
  host:
    - libabseil
    - libprotobuf
    - protobuf-bazel-rules

test:
  commands:
    - test -f $PREFIX/bin/singlejar
    - test -f $PREFIX/bin/singlejar_local

about:
  home: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: A tool for generating singleton jars

extra:
  recipe-maintainers:
    - xhochy
    - h-vetinari
    - conda-forge/bazel
