{% set version = "8.7.0rc1" %}

{% set base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: singlejar
  version: {{ version }}

source:
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: c176c19773d4ec86c4ec0a7d21355a6b3f607238dad3ce3018152397542a2157
    patches:
      # Keep these patches in sync with the relevant ones from bazel-feedstock.
      - patches/0001-allow-args-to-be-passed-to-bazel_build.patch
      - patches/0002-Build-with-native-dependencies.patch
      - patches/0003-use-C-17.patch

  - fn: bazel-{{ version }}
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64   # [build_platform == "linux-64"]
    sha256: 425ce4439252e643bc8a12eecaeb52878b63602956548f46c54378cb7b3699a3   # [build_platform == "linux-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-x86_64  # [build_platform == "osx-64"]
    sha256: 4f46ebc4b8498a017343139cdc6f92aa5b1fbe1d4872a1064a3663ab5bcc0019   # [build_platform == "osx-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64   # [build_platform == "osx-arm64"]
    sha256: ee973ce0daadbe867e589be5fa1e146a70e10380aec6ef41cabb29994764e983   # [build_platform == "osx-arm64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain >=0.2.0
    - openjdk
    - libprotobuf
    - sed
  host:
    - libabseil
    - libprotobuf
    - protobuf-bazel-rules

test:
  commands:
    - test -f $PREFIX/bin/singlejar
    - test -f $PREFIX/bin/singlejar_local

about:
  home: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: A tool for generating singleton jars

extra:
  recipe-maintainers:
    - xhochy
    - h-vetinari
    - conda-forge/bazel
