schema_version: 1

context:
  version: "9.2.0"
  base_url: https://github.com/bazelbuild/bazel/releases/download

package:
  name: singlejar
  version: ${{ version }}

source:
  - url: ${{ base_url }}/${{ version }}/bazel-${{ version }}-dist.zip
    sha256: 81af02b33128ec1922c6b60212df3fb6150baa96bb33d32ffa020e5fed47fefc
    patches:
      # Keep these patches in sync with the relevant ones from bazel-feedstock.
      - patches/0001-allow-args-to-be-passed-to-bazel_build.patch
      - patches/0002-Build-with-native-dependencies.patch
  - if: build_platform == "linux-64"
    then:
      url: ${{ base_url }}/${{ version }}/bazel_nojdk-${{ version }}-linux-x86_64
      sha256: 9cf3498e6d132b60ca90b1390499a07265084d4707e98c128c13c284da4c470f
      file_name: bazel-${{ version }}
  - if: build_platform == "linux-aarch64"
    then:
      url: ${{ base_url }}/${{ version }}/bazel_nojdk-${{ version }}-linux-arm64
      sha256: c3cea37c78285a9b1877be88f55277bc45acf960e006c64e8941c1f6cf1cab65
      file_name: bazel-${{ version }}
  - if: build_platform == "osx-64"
    then:
      url: ${{ base_url }}/${{ version }}/bazel_nojdk-${{ version }}-darwin-x86_64
      sha256: 1549242b08b18af3e5df3b1023ed286a422d1a262ef81df3579c529749429cba
      file_name: bazel-${{ version }}
  - if: build_platform == "osx-arm64"
    then:
      url: ${{ base_url }}/${{ version }}/bazel_nojdk-${{ version }}-darwin-arm64
      sha256: 7172ba73079d60cb4201d51ba9be2ebf08651c689eed42c5840eba41c9081cf6
      file_name: bazel-${{ version }}

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - bazel-toolchain >=0.5.8
    - openjdk
    - libprotobuf
    - sed
  host:
    - libabseil
    - libabseil-bazel-systemlib
    - libprotobuf
    - libprotobuf-bazel-systemlib
    - protobuf-bazel-rules

tests:
  - script:
      - test -f $PREFIX/bin/singlejar
      - test -f $PREFIX/bin/singlejar_local

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: A tool for generating singleton jars
  homepage: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar

extra:
  recipe-maintainers:
    - xhochy
    - h-vetinari
    - conda-forge/bazel
