schema_version: 1

context:
  version: "9.1.0"
  base_url: https://github.com/bazelbuild/bazel/releases/download

package:
  name: singlejar
  version: ${{ version }}

source:
  - url: ${{ base_url }}/${{ version }}/bazel-${{ version }}-dist.zip
    sha256: 229e999cec4f408946d368af6c33c5137fe999e9966538562f8c90b0de7aa0ad
    patches:
      # Keep these patches in sync with the relevant ones from bazel-feedstock.
      - patches/0001-allow-args-to-be-passed-to-bazel_build.patch
      - patches/0002-Build-with-native-dependencies.patch
  - if: build_platform == "linux-64"
    then:
      url: ${{ base_url }}/${{ version }}/bazel_nojdk-${{ version }}-linux-x86_64
      sha256: 5d9a612f5d0827ac0ce805e52d33fe0517348938e3691cd3c609e06eba858067
      file_name: bazel-${{ version }}
  - if: build_platform == "osx-64"
    then:
      url: ${{ base_url }}/${{ version }}/bazel_nojdk-${{ version }}-darwin-x86_64
      sha256: be54bc6d9b6c1e071acaeddd40c81a4836555c6f514ceff00680624156102ffd
      file_name: bazel-${{ version }}
  - if: build_platform == "osx-arm64"
    then:
      url: ${{ base_url }}/${{ version }}/bazel_nojdk-${{ version }}-darwin-arm64
      sha256: 27c0a94687e4cf7d27c04a38ad33c26f4be9c91b8d29cc70c7f48dce625dd420
      file_name: bazel-${{ version }}

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - bazel-toolchain >=0.5.8
    - openjdk
    - libprotobuf
    - sed
  host:
    - libabseil
    - libabseil-bazel-systemlib
    - libprotobuf
    - libprotobuf-bazel-systemlib
    - protobuf-bazel-rules

tests:
  - script:
      - test -f $PREFIX/bin/singlejar
      - test -f $PREFIX/bin/singlejar_local

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: A tool for generating singleton jars
  homepage: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar

extra:
  recipe-maintainers:
    - xhochy
    - h-vetinari
    - conda-forge/bazel
