schema_version: 1

context:
  version: "9.1.1"
  base_url: https://github.com/bazelbuild/bazel/releases/download

package:
  name: singlejar
  version: ${{ version }}

source:
  - url: ${{ base_url }}/${{ version }}/bazel-${{ version }}-dist.zip
    sha256: a6f66e26c8f4ca04fa83c796a404eff0544bd78336fbbcd122c9e10cbec4a5d7
    patches:
      # Keep these patches in sync with the relevant ones from bazel-feedstock.
      - patches/0001-allow-args-to-be-passed-to-bazel_build.patch
      - patches/0002-Build-with-native-dependencies.patch
  - if: build_platform == "linux-64"
    then:
      url: ${{ base_url }}/${{ version }}/bazel_nojdk-${{ version }}-linux-x86_64
      sha256: 27ab26da32952a93c31e93239327e99ea41d23d5074e5ec3e326af96a8f34887
      file_name: bazel-${{ version }}
  - if: build_platform == "osx-64"
    then:
      url: ${{ base_url }}/${{ version }}/bazel_nojdk-${{ version }}-darwin-x86_64
      sha256: 8606b14e335d10de6cd22c527b05a0fcaf85760c2dc158219f39128441ab2ae4
      file_name: bazel-${{ version }}
  - if: build_platform == "osx-arm64"
    then:
      url: ${{ base_url }}/${{ version }}/bazel_nojdk-${{ version }}-darwin-arm64
      sha256: c079130049a63710f67dcb4133cf6d9384fa12e46b4efce6ce8183a83f6c4342
      file_name: bazel-${{ version }}

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - bazel-toolchain >=0.5.8
    - openjdk
    - libprotobuf
    - sed
  host:
    - libabseil
    - libabseil-bazel-systemlib
    - libprotobuf
    - libprotobuf-bazel-systemlib
    - protobuf-bazel-rules

tests:
  - script:
      - test -f $PREFIX/bin/singlejar
      - test -f $PREFIX/bin/singlejar_local

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: A tool for generating singleton jars
  homepage: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar

extra:
  recipe-maintainers:
    - xhochy
    - h-vetinari
    - conda-forge/bazel
